#!/usr/bin/env bash
# scripts/install_hooks.sh
# ------------------------
# Install the pre-commit hook that auto-updates AGENT.md before each commit.
# Run once after cloning the repository:
#
#   bash scripts/install_hooks.sh
#

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
HOOK_FILE="$HOOKS_DIR/pre-commit"

cat > "$HOOK_FILE" << 'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install_hooks.sh
# Updates AGENT.md timestamp before each commit.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
PYTHON="$(command -v python3 || command -v python)"

"$PYTHON" "$REPO_ROOT/scripts/update_agent_md.py"
git add "$REPO_ROOT/AGENT.md"
EOF

chmod +x "$HOOK_FILE"
echo "✅ Pre-commit hook installed at $HOOK_FILE"
